### ISSUE TITLE
License

### ISSUE THREAD

**Issue by antonengelhardt** [sonhal/wasm-oauth-filter#6]
Hello @sonhal,

Could you add a license to this repo? I will develop something similar for my bachelor thesis and found this repo very helpful.

Also, are you planning to work on this repo? Is it still maintained?

Thx!

**Comment by WestFarmer** [comment]
@antonengelhardt if you ever noticed my three issues got ignored, you should know this repo is not maintained.. 
but I am also trying to find a production-ready BFF or service-mesh solution (like this one) for SPAs.
if you are interested, maybe we can help each other

**Comment by antonengelhardt** [comment]
Hey @WestFarmer,

Thanks for your reply. I noticed that's aswell but I wanted to try my luck 😁

Actually, I'm kinda new to Kubernetes, Istio etc. I found this repo, because I have to write my bachelor thesis about the development of a Wasm plugin which can be attached to an envoy Filter. Not sure, if I can help you here...

**Comment by antonengelhardt** [comment]
Hey @WestFarmer,
I am almost done with my project and I'm thinking about making it public. 

Did you also implement something ?
